In [7]:
import numpy as np

In [9]:
import pandas as pd

In [11]:
from scipy.stats import norm

In [12]:
import yfinance as yf

In [13]:
data=pd.read_excel("C:/Users/balak/Anaconda Scripts/input data/WCDR Stressed loss.xlsx")
data

#all amounts in $mn

          EAD        PD       LGD
0    2.111343  0.202368  0.351696
1    5.299065  0.050000  0.339039
2    7.658582  0.881373  0.690649
3   10.038626  0.040000  0.248444
4    3.382498  0.195809  0.476928
..        ...       ...       ...
95   9.516058  0.050000  0.277500
96  10.335128  0.088985  0.420730
97   3.282769  0.050000  0.678958
98  10.832903  0.804299  0.622169
99   4.187617  0.050000  0.627657

[100 rows x 3 columns]

In [14]:
#Correlation = 0.12 + 0.24*e^(-50*PD)
#WCDR=NORM.S.DIST((NORM.S.INV(PD)+(SQRT(Correlation)*NORM.S.INV(confidence_level)))/SQRT(1-Correlation))
#Expected Loss (EL) = EAD x PD x LGD
#Stressed Loss (SL) = EAD x WCDR x LGD
#Unexpected Loss (UL) = Stressed Loss (SL) - Expected Loss (EL)

In [15]:
data['Correlation']=0.12+(0.24*(np.exp(data['PD']*(-50))))
confidence_level=0.999
data['WCDR']=norm.cdf((norm.ppf(data['PD'])+(np.sqrt(data['Correlation'])*norm.ppf(confidence_level)))/(np.sqrt(1-data['Correlation'])))
data['EL']=data['EAD']*data['PD']*data['LGD']
data['SL']=data['EAD']*data['WCDR']*data['LGD']
data['UL']=data['SL']-data['EL']
data

,EAD,PD,LGD,Correlation,WCDR,EL,SL,UL
0,2.111343,0.202368,0.351696,0.120010,0.599868,0.150268,0.445432,0.295164
1,5.299065,0.050000,0.339039,0.139700,0.298712,0.089829,0.536663,0.446833
2,7.658582,0.881373,0.690649,0.120000,0.991826,4.661930,5.246156,0.584226
3,10.038626,0.040000,0.248444,0.152480,0.277293,0.099761,0.691579,0.591817
4,3.382498,0.195809,0.476928,0.120013,0.590169,0.315881,0.952065,0.636184
...,...,...,...,...,...,...,...,...
95,9.516058,0.050000,0.277500,0.139700,0.298712,0.132035,0.788810,0.656775
96,10.335128,0.088985,0.420730,0.122805,0.388977,0.386934,1.691389,1.304455
97,3.282769,0.050000,0.678958,0.139700,0.298712,0.111443,0.665788,0.554345
98,10.832903,0.804299,0.622169,0.120000,0.980050,5.420891,6.605436,1.184545
99,4.187617,0.050000,0.627657,0.139700,0.298712,0.131419,0.785131,0.653712

In [16]:
Expected_Loss=np.sum(data['EL'])
Stressed_Loss=np.sum(data['SL'])
Unexpected_Loss=np.sum(data['UL'])

print('Expected_Loss = $',Expected_Loss,'mn')
print('Stressed_Loss = $',Stressed_Loss,'mn')
print('Unexpected_Loss = $',Unexpected_Loss,'mn')

Expected_Loss = $ 72.82650070369206 mn
Stressed_Loss = $ 141.56448680403614 mn
Unexpected_Loss = $ 68.73798610034407 mn

In [23]:
Capital_Required=Unexpected_Loss
print('Capital_Required = $',Capital_Required,'mn')

Capital_Required = $ 68.73798610034407 mn